name: Hololive Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select a name for the holomen"
        type: choice
        default: "ときのそら"
        required: true
        options:
          - ときのそら
          - 星街すいせい
          - さくらみこ
          - AZKi
          - 天音かなた
          - 雪花ラミィ

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.select_holomen.env }}"
