name: Hololive Workflow

on:
  workflow_dispatch:
    inputs:
      select_holomen:
        type: string
        default: Hello
        required: true
        description: Select a name for the holomen
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.select_holomen }}"
