# name: Generate functions
# on: push
# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     steps:
#       - run: printenv | grep '_FUNC'
#         env:
#           FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }}
#           JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}

# name: Status check functions
# on:
#   push:
#     branches:
#       - workflow-test

# jobs:
#   skip-or-run:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello"
#       if: ${{ contains(github.run_id, '1') }}

# jobs:
#   fail:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
#       - run: echo "Hello"
#         if: ${{ failure() }}

# name: Run name
# run-name: Run by @${{ github.actor }}
# on:
#   push:
#     branches:
#       - workflow-test

# jobs:
#   print:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Hello"

# name: Missing share data
# on:
#   push:
#     branches:
#       - workflow-test

# jobs:
#   share:
#     runs-on: ubuntu-latest
#     steps:
#       - id: source
#         run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
#       - env:
#           RESULT: ${{ steps.source.outputs.result }}
#         run: echo "${RESULT}"

# name: Change shell
# on: push
# jobs:
#   print:
#     runs-on: ubuntu-latest
#     steps:
#       - shell: bash
#         run: echo "${SHELL}"
#       - shell: python
#         run: |
#           import os
#           print(os.environ['PATH'])

name: Environments
on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" 